In [6]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [8]:
env = gym.make('LQ-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=40000)

z shape: (?, 3)
********** Iteration 1 ************
[[ 1.1777662   0.16071616 -0.01152174]
 [ 0.16071616  1.161256    0.00873932]
 [-0.01152174  0.00873932  1.0928861 ]]
	Episode Len: 100
	Last Episode Cost: 1148.067513 vs optimal 0.000000
********** Iteration 2 ************
[[1.3207072  0.3175016  0.04086336]
 [0.3175016  1.3629165  0.09843192]
 [0.04086336 0.09843192 1.1700716 ]]
	Episode Len: 1
	Last Episode Cost: 0.206874 vs optimal 5.641392
********** Iteration 3 ************
[[1.4785506  0.5152906  0.11999181]
 [0.5152906  1.6374657  0.21718276]
 [0.11999181 0.21718276 1.2325277 ]]
	Episode Len: 100
	Last Episode Cost: 353.632437 vs optimal 6.059928
********** Iteration 4 ************
[[1.6273493  0.7064905  0.19617477]
 [0.7064905  1.9042882  0.32936662]
 [0.19617477 0.32936662 1.293458  ]]
	Episode Len: 100
	Last Episode Cost: 1337.048640 vs optimal 6.444146
********** Iteration 5 ************
[[1.7598736  0.87938225 0.2658687 ]
 [0.87938225 2.1463232  0.43001345]
 [0.2658687  

[-24.73451836271854,
 -24.260692828284864,
 -69.02591001857161,
 -46.43323848122717,
 -37.012995199923886,
 -48.33379586089251,
 -80.16712709862915,
 -137.07634433605313,
 -267.76581911114243,
 -934.1269915475551,
 -3505.679754422602,
 -74402.94155742203,
 -22901.662248991615,
 -20164.189683969285,
 -19241.268016676135,
 -66.43763895619853,
 -1591.7981484305562,
 -14794.954587606284,
 -17109.663273664864,
 -18760.70625675459,
 -16867.847944160054,
 -6077.574810529455,
 -1646.861825125171,
 -457.9432668695529,
 -251.5135980310549,
 -368.5397711921571,
 -488.9923560002121,
 -870.979854401916,
 -663.1100005985654,
 -1702.0826269545971,
 -4856.023338123502,
 -8689.83659812637,
 -16294.933282606811,
 -14227.7552015281,
 -7808.850541693858,
 -12392.127565457671,
 -9854.99833425425,
 -12484.631637651015,
 -25962.026784463254,
 -23332.976269556697,
 -17696.3326795212,
 -13981.562150231444,
 -16083.72506166172,
 -14057.926744989501,
 -12016.636031764077,
 -11827.014302359637,
 -8462.58484001108

In [14]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
s reset: [[0.01337004]
 [1.62633227]
 [0.65070641]]
s reset: [[ 0.60735712]
 [-1.61890631]
 [ 1.38426126]]
s init: [0.6073571212559301, -1.6189063113379798, 1.384261257596441]
Optimal cost for this problem: 8.077039842009057
	Last Episode Reward: -5.322727
********** Iteration 2 ************
s reset: [[-0.26485418]
 [ 1.50918456]
 [-0.73740952]]
s init: [-0.26485417638315045, 1.5091845563926518, -0.7374095206304747]
Optimal cost for this problem: 5.15022044581315
	Last Episode Reward: -3.213320
********** Iteration 3 ************
s reset: [[ 0.57373878]
 [ 1.73360438]
 [-0.75888664]]
s init: [0.5737387842174053, 1.733604383715372, -0.758886640650422]
Optimal cost for this problem: 8.573453475724394
	Last Episode Reward: -2.289193
********** Iteration 4 ************
s reset: [[-1.18998038]
 [-1.18867163]
 [-0.49698327]]
s init: [-1.1899803820377524, -1.1886716277379619, -0.49698327279151133]
Optimal cost for this problem: 9.468425087645812
	Last Episo

In [16]:
sess.run(agent.A)

array([[-8.9205016e-04,  5.9654236e-01,  4.4267657e-04],
       [-6.8791264e-01, -5.9567159e-01,  6.8911929e-03],
       [-5.4085419e-02, -4.3130752e-01, -7.8866673e-01]], dtype=float32)

In [17]:
sess.run(agent.B)

array([[-0.9018039 ,  1.8478922 , -0.43067294],
       [-1.6550338 , -1.1298691 ,  0.8423557 ],
       [ 0.3802839 , -0.54053843, -1.9705842 ]], dtype=float32)