In [61]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [62]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [63]:
env = gym.make('TransformedLQ-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=40000, n_transitions_between_updates=100,
                n_optim_steps_per_update=200,
                n_iters_per_p_update=5,
                )

z shape: (?, 3)
********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 1000.198564 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 2154.474729 vs optimal 159.129151
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 935.682579 vs optimal 3.579493
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 3474.880768 vs optimal 92.262451
********** Iteration 5 ************
[[ 1.1403294   0.08918885 -0.05736694]
 [ 0.08918885  1.0763159  -0.06799618]
 [-0.05736694 -0.06799618  1.0904975 ]]
	Episode Len: 100
	Last Episode Cost: 2587.908359 vs optimal 43.027278
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 3059.761036 vs optimal 118.497037
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 950.808889 vs optimal 74.885102
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 348.773859 vs optimal 45.284650
********** It

In [64]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 139.767637 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 48.441955 vs optimal 20.348540
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 213.994442 vs optimal 106.598036
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 116.515674 vs optimal 71.598329
********** Iteration 5 ************
	Episode Len: 100
	Last Episode Cost: 174.349971 vs optimal 68.801350
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 98.024380 vs optimal 46.513973
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 226.763391 vs optimal 109.668721
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 14.844323 vs optimal 5.612408
********** Iteration 9 ************
	Episode Len: 100
	Last Episode Cost: 281.585592 vs optimal 93.762568
********** Iteration 10 ************
	Episode Len

In [56]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 915.910508 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 922.012108 vs optimal 16.436779
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 1117.233503 vs optimal 61.685952
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 948.558038 vs optimal 14.255025
********** Iteration 5 ************
	Episode Len: 100
	Last Episode Cost: 913.919872 vs optimal 101.965660
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 1090.863860 vs optimal 219.421257
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 1064.240353 vs optimal 225.311849
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 1262.386139 vs optimal 39.287106
********** Iteration 9 ************
	Episode Len: 100
	Last Episode Cost: 938.289780 vs optimal 3.604805
********** Iteration 10 ************
	Epi

In [65]:
sess.run(agent.A)

array([[-5.3853601e-02,  8.9006731e-05, -3.4367201e+00],
       [-4.7361150e-01, -4.2706448e-05, -2.0157264e-01],
       [-1.0361968e-03,  7.3502929e-04, -5.5850679e-03]], dtype=float32)

In [66]:
sess.run(agent.B)

array([[-0.12942345, -0.26122615,  0.4155125 ],
       [-0.01761237,  0.01989609, -0.01651877],
       [-0.10424881,  0.739078  , -0.8938714 ]], dtype=float32)

In [67]:
sess.run(agent.Q)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [68]:
sess.run(agent.R)

array([[26.033157 ,  6.7706137, -2.7430046],
       [ 6.7706137, 13.15794  ,  8.054715 ],
       [-2.7430046,  8.054715 , 12.383449 ]], dtype=float32)

In [40]:
A,B,Q,R = (env.env.A, env.env.B, env.env.Q, env.env.R)
P = Q
for k in range(100):
    P = Q + A.T @ P @ A - A.T @ P.T @ B @ np.linalg.inv(R + B.T @ P @ B ) @ B.T @ P @ A
    P = 0.5*(P + P.T)

In [41]:
P

array([[2.23999771, 0.54694411, 0.19286546],
       [0.54694411, 2.35082156, 0.54694411],
       [0.19286546, 0.54694411, 2.23999771]])

In [42]:
sess.run(agent.P)

array([[1.7117685 , 0.55636847, 0.07273098],
       [0.55636847, 1.7515693 , 0.6495986 ],
       [0.07273098, 0.6495986 , 1.8076872 ]], dtype=float32)