In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

In [2]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [3]:
env = gym.make('LQ-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=40000)

z shape: (?, 3)
********** Iteration 1 ************
Optimal cost for this problem: 14.078417703688306
[[ 0.5949104   0.01723212 -0.4021873 ]
 [ 0.01723212  2.2583718  -0.5354465 ]
 [-0.4021873  -0.5354465   1.0991429 ]]
	Last Episode Reward: -734
********** Iteration 2 ************
Optimal cost for this problem: 0.8679269093056176
[[ 0.74871373 -0.04579777 -0.27331132]
 [-0.04579777  3.6459193   0.04387701]
 [-0.27331132  0.04387701  1.2694242 ]]
	Last Episode Reward: -1163
********** Iteration 3 ************
Optimal cost for this problem: 9.257681793804467
[[ 0.88226867 -0.32462257 -0.2584813 ]
 [-0.32462257  4.4979568   0.25873005]
 [-0.2584813   0.25873005  1.4498641 ]]
	Last Episode Reward: -7318
********** Iteration 4 ************
Optimal cost for this problem: 8.95773037896098
[[ 1.0205572  -0.4978631  -0.27925065]
 [-0.4978631   5.0276456   0.41639397]
 [-0.27925065  0.41639397  1.6409516 ]]
	Last Episode Reward: -827
********** Iteration 5 ************
Optimal cost for this pro

In [14]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
s reset: [[0.01337004]
 [1.62633227]
 [0.65070641]]
s reset: [[ 0.60735712]
 [-1.61890631]
 [ 1.38426126]]
s init: [0.6073571212559301, -1.6189063113379798, 1.384261257596441]
Optimal cost for this problem: 8.077039842009057
	Last Episode Reward: -5.322727
********** Iteration 2 ************
s reset: [[-0.26485418]
 [ 1.50918456]
 [-0.73740952]]
s init: [-0.26485417638315045, 1.5091845563926518, -0.7374095206304747]
Optimal cost for this problem: 5.15022044581315
	Last Episode Reward: -3.213320
********** Iteration 3 ************
s reset: [[ 0.57373878]
 [ 1.73360438]
 [-0.75888664]]
s init: [0.5737387842174053, 1.733604383715372, -0.758886640650422]
Optimal cost for this problem: 8.573453475724394
	Last Episode Reward: -2.289193
********** Iteration 4 ************
s reset: [[-1.18998038]
 [-1.18867163]
 [-0.49698327]]
s init: [-1.1899803820377524, -1.1886716277379619, -0.49698327279151133]
Optimal cost for this problem: 9.468425087645812
	Last Episo

In [16]:
sess.run(agent.A)

array([[-8.9205016e-04,  5.9654236e-01,  4.4267657e-04],
       [-6.8791264e-01, -5.9567159e-01,  6.8911929e-03],
       [-5.4085419e-02, -4.3130752e-01, -7.8866673e-01]], dtype=float32)

In [17]:
sess.run(agent.B)

array([[-0.9018039 ,  1.8478922 , -0.43067294],
       [-1.6550338 , -1.1298691 ,  0.8423557 ],
       [ 0.3802839 , -0.54053843, -1.9705842 ]], dtype=float32)