In [24]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [43]:
env = gym.make('Pendulum-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=40000, n_transitions_between_updates=100,
                n_optim_steps_per_update=200,
                n_iters_per_p_update=5,
                )

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
z shape: (?, 3)
********** Iteration 1 ************
	Episode Len: 0
	Last Episode Cost: 0.000000 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 200
	Last Episode Cost: 1045.182119 vs optimal 0.000000
********** Iteration 3 ************
	Episode Len: 200
	Last Episode Cost: 1045.182119 vs optimal 0.000000
********** Iteration 4 ************
	Episode Len: 200
	Last Episode Cost: 1268.661989 vs optimal 0.000000
********** Iteration 5 ************
[[ 1.0930681  -0.10070159  0.02992011]
 [-0.10070159  1.2747712  -0.01498683]
 [ 0.02992011 -0.01498683  1.246289  ]]
	Episode Len: 200
	Last Episode Cost: 1268.661989 vs optimal 0.000000
********** Iteration 6 ************
	Episode Len: 200
	Last Episode Cost: 1035.799770 vs optimal 0.000000
********** Iteration 7 ************
	

In [44]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 0
	Last Episode Cost: 0.000000 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 200
	Last Episode Cost: 1355.410647 vs optimal 0.000000
********** Iteration 3 ************
	Episode Len: 200
	Last Episode Cost: 1355.410647 vs optimal 0.000000
********** Iteration 4 ************
	Episode Len: 200
	Last Episode Cost: 1081.270081 vs optimal 0.000000
********** Iteration 5 ************
	Episode Len: 200
	Last Episode Cost: 1081.270081 vs optimal 0.000000
********** Iteration 6 ************
	Episode Len: 200
	Last Episode Cost: 1333.943959 vs optimal 0.000000
********** Iteration 7 ************
	Episode Len: 200
	Last Episode Cost: 1333.943959 vs optimal 0.000000
********** Iteration 8 ************
	Episode Len: 200
	Last Episode Cost: 1353.324255 vs optimal 0.000000
********** Iteration 9 ************
	Episode Len: 200
	Last Episode Cost: 1353.324255 vs optimal 0.000000
********** Iteration 10 ************
	Episode Len: 

In [13]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 15.114967 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 2.847836 vs optimal 2.355781
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 12.386197 vs optimal 11.864259
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 13.126852 vs optimal 11.716004
********** Iteration 5 ************
	Episode Len: 100
	Last Episode Cost: 8.160144 vs optimal 7.246125
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 12.285117 vs optimal 11.117412
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 8.954077 vs optimal 7.739204
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 14.499120 vs optimal 13.201736
********** Iteration 9 ************
	Episode Len: 100
	Last Episode Cost: 5.719255 vs optimal 5.130324
********** Iteration 10 ************
	Episode Len: 100
	Last Epi

In [34]:
sess.run(agent.A)

array([[ 0.9928766 ,  0.01346777,  0.00223179],
       [ 0.00369994,  1.0001762 , -0.0268475 ],
       [-0.00469956,  0.7248061 ,  0.9946641 ]], dtype=float32)

In [35]:
sess.run(agent.B)

array([[0.01191544],
       [0.01951253],
       [0.1294254 ]], dtype=float32)

In [37]:
sess.run(agent.Q)

array([[ 6.2274194 ,  0.16746204,  0.01383346],
       [ 0.16746204,  2.2038727 , -0.02676243],
       [ 0.01383346, -0.02676243,  0.13703305]], dtype=float32)

In [38]:
sess.run(agent.R)

array([[0.17767526]], dtype=float32)

In [40]:
A,B,Q,R = (env.env.A, env.env.B, env.env.Q, env.env.R)
P = Q
for k in range(100):
    P = Q + A.T @ P @ A - A.T @ P.T @ B @ np.linalg.inv(R + B.T @ P @ B ) @ B.T @ P @ A
    P = 0.5*(P + P.T)

In [41]:
P

array([[2.23999771, 0.54694411, 0.19286546],
       [0.54694411, 2.35082156, 0.54694411],
       [0.19286546, 0.54694411, 2.23999771]])

In [42]:
sess.run(agent.P)

array([[1.7117685 , 0.55636847, 0.07273098],
       [0.55636847, 1.7515693 , 0.6495986 ],
       [0.07273098, 0.6495986 , 1.8076872 ]], dtype=float32)