In [9]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [11]:
env = gym.make('LQ-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=40000, n_transitions_between_updates=100,
                n_optim_steps_per_update=200,
                n_iters_per_p_update=10,
                )

z shape: (?, 3)
********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 515.724559 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 493.139439 vs optimal 3.215927
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 1289.636483 vs optimal 8.607508
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 293.003399 vs optimal 16.047868
********** Iteration 5 ************
[[1.0030875  0.02284391 0.00250957]
 [0.02284391 1.2498713  0.00792627]
 [0.00250957 0.00792627 1.0506517 ]]
	Episode Len: 100
	Last Episode Cost: 815.344650 vs optimal 6.366977
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 717.137413 vs optimal 0.165178
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 535.783350 vs optimal 11.476054
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 386.160677 vs optimal 2.901625
********** Iteration 9 *********

In [12]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 23.058282 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 29.417273 vs optimal 6.350504
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 75.579351 vs optimal 9.672382
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 34.834008 vs optimal 6.242103
********** Iteration 5 ************
	Episode Len: 100
	Last Episode Cost: 38.708545 vs optimal 4.071505
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 25.648815 vs optimal 9.807990
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 24.554620 vs optimal 5.869234
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 20.497342 vs optimal 9.068296
********** Iteration 9 ************
	Episode Len: 100
	Last Episode Cost: 37.108388 vs optimal 15.079566
********** Iteration 10 ************
	Episode Len: 100
	Last Ep

In [56]:
#test

agent.max_a = 100.0
agent.min_a = -100.0
train_agent(agent,env,max_timesteps=1000,training=False)

********** Iteration 1 ************
	Episode Len: 100
	Last Episode Cost: 915.910508 vs optimal 0.000000
********** Iteration 2 ************
	Episode Len: 100
	Last Episode Cost: 922.012108 vs optimal 16.436779
********** Iteration 3 ************
	Episode Len: 100
	Last Episode Cost: 1117.233503 vs optimal 61.685952
********** Iteration 4 ************
	Episode Len: 100
	Last Episode Cost: 948.558038 vs optimal 14.255025
********** Iteration 5 ************
	Episode Len: 100
	Last Episode Cost: 913.919872 vs optimal 101.965660
********** Iteration 6 ************
	Episode Len: 100
	Last Episode Cost: 1090.863860 vs optimal 219.421257
********** Iteration 7 ************
	Episode Len: 100
	Last Episode Cost: 1064.240353 vs optimal 225.311849
********** Iteration 8 ************
	Episode Len: 100
	Last Episode Cost: 1262.386139 vs optimal 39.287106
********** Iteration 9 ************
	Episode Len: 100
	Last Episode Cost: 938.289780 vs optimal 3.604805
********** Iteration 10 ************
	Epi

In [85]:
sess.run(agent.A)

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]], dtype=float32)

In [84]:
sess.run(agent.B)

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [83]:
sess.run(agent.Q)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [82]:
sess.run(agent.R)

array([[nan]], dtype=float32)

In [40]:
A,B,Q,R = (env.env.A, env.env.B, env.env.Q, env.env.R)
P = Q
for k in range(100):
    P = Q + A.T @ P @ A - A.T @ P.T @ B @ np.linalg.inv(R + B.T @ P @ B ) @ B.T @ P @ A
    P = 0.5*(P + P.T)

In [41]:
P

array([[2.23999771, 0.54694411, 0.19286546],
       [0.54694411, 2.35082156, 0.54694411],
       [0.19286546, 0.54694411, 2.23999771]])

In [42]:
sess.run(agent.P)

array([[1.7117685 , 0.55636847, 0.07273098],
       [0.55636847, 1.7515693 , 0.6495986 ],
       [0.07273098, 0.6495986 , 1.8076872 ]], dtype=float32)