In [35]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import gym
from collections import deque
import random
import time
import yaml
from klqr import *
from train_utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
with open('config.yml','r') as ymlfile:
    config = yaml.load(ymlfile)
    
tf.reset_default_graph()
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))

In [37]:
env = gym.make('Pendulum-v0')
agent = klqr(config,sess)
agent.build_model()
train_agent(agent,env,max_timesteps=100000)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
z shape: (?, 6)
********** Iteration 1 ************
	Last Episode Reward: 0
********** Iteration 2 ************
	Last Episode Reward: -1028
********** Iteration 3 ************
	Last Episode Reward: -1028
********** Iteration 4 ************
	Last Episode Reward: -1128
********** Iteration 5 ************
	Last Episode Reward: -1128
********** Iteration 6 ************
	Last Episode Reward: -894
********** Iteration 7 ************
	Last Episode Reward: -894
********** Iteration 8 ************
	Last Episode Reward: -890
********** Iteration 9 ************
	Last Episode Reward: -890
********** Iteration 10 ************
	Last Episode Reward: -976
********** Iteration 11 ************
	Last Episode Reward: -976
********** Iteration 12 ************
	Last Episode Reward: -864
********** Iteration 13 **

KeyboardInterrupt: 

In [ ]:
env.action_space

In [38]:
A = sess.run(agent.A)

In [39]:
print(np.round(A*100)/100)

[[ 0.   -0.    0.    0.   -0.08 -0.  ]
 [ 0.    0.4  -0.06  0.   -0.06  0.19]
 [ 0.    0.    0.59  0.   -0.01 -0.51]
 [-0.    0.    0.    0.68 -0.27  0.13]
 [-0.   -0.   -0.08 -0.24  0.78 -0.  ]
 [ 0.    0.04  0.   -0.02 -0.    0.95]]


In [40]:
sess.run(agent.B)

array([[-0.00648174],
       [ 0.00433212],
       [-0.02874016],
       [ 0.00784383],
       [-0.01057139],
       [ 0.00829484]], dtype=float32)

In [41]:
sess.run(agent.Q)

array([[ 0.44878745,  0.10372268, -0.04940924, -0.02321559, -0.28664175,
         0.02329656],
       [ 0.10372268,  1.0297765 , -0.8721553 ,  0.34143567,  0.12583704,
         0.56099135],
       [-0.04940924, -0.8721553 ,  1.1417718 , -0.73204386, -0.17271739,
        -0.44206622],
       [-0.02321559,  0.34143567, -0.73204386,  1.1944157 , -0.37650794,
         0.46224195],
       [-0.28664175,  0.12583703, -0.17271736, -0.3765079 ,  1.0999533 ,
         0.23865563],
       [ 0.02329657,  0.56099135, -0.44206622,  0.46224198,  0.23865563,
         0.9965708 ]], dtype=float32)